### ISSUE TITLE
Why distribute sqlite3.{c,h}

### ISSUE THREAD

**Issue by markuman** [siscia/rediSQL#2]
Why do you distribute sqlite3.{c,h}? Imho it's easier to take it from the packagemanager provided by the operating system.

    apk add sqlite-dev sqlite-libs # alpine
    pacman -S sqlite3 # arch
    apt-get install libsqlite3-0 libsqite3-dev # debian
    brew install sqlite # plastic os
    zypper install libsqlite3-0 sqlite3-devel # some old rpm distros
    dnf install sqlite-devel sqlite-libs # fedora

**Comment by siscia** [comment]
It will definitely be easier, however in this way I have more control on how sqlite3 is compiled. For now it doesn't change anything, tomorrow it may.

**Comment by siscia** [comment]
@markuman please if you are satisfied with my answer close the issue ;)
